# Use an official Python runtime as a base image
FROM jrs65/python-mysql

## The maintainer name and email
MAINTAINER Richard Shaw <richard@phas.ubc.ca>

# Install any needed packages specified in requirements.txt
COPY requirements.txt /build_req/
COPY test-requirements.txt /build_req/
RUN pip install -r /build_req/requirements.txt
RUN pip install -r /build_req/test-requirements.txt

# Copy the configuration file, and create the log directory
COPY tests/docker/alpenhorn.conf /etc/alpenhorn/alpenhorn.conf
RUN mkdir /var/log/alpenhorn

ADD . /build
RUN pip install /build

CMD alpenhornd
