## Generate an image that automatically starts alpenhornd and sshd (for
## transfers)

# Use an official Python runtime as a base image
FROM python:3.8

LABEL maintainer="Richard Shaw <richard@phas.ubc.ca>"

# System prerequisites for the test image
RUN apt-get update && apt-get install --no-install-recommends -y \
    ssh \
    rsync \
    netcat \
    default-mysql-client
RUN pip install --no-cache-dir mysqlclient

# Set up ssh key based login for root
RUN ssh-keygen -t rsa -N '' -f /root/.ssh/id_rsa
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
RUN echo 'Host *\n\
    StrictHostKeyChecking no\n' > /root/.ssh/config

# Make port 22 available to the world outside this container
EXPOSE 22

# Copy the configuration file and create the log directory
COPY tests/docker/alpenhorn.conf /etc/alpenhorn/alpenhorn.conf
RUN mkdir /var/log/alpenhorn

# Install the custom acq and file types
COPY tests/docker/custom_test_types.py /root/python/custom_test_types.py
ENV PYTHONPATH /root/python/

# Install any needed packages specified in requirements.txt
WORKDIR /build
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install alpenhorn
ADD . /build
RUN pip install --no-deps .

# Run alpenhorn and ssh
CMD service ssh start && \
    alpenhornd
