# Use an official Python runtime as a base image
FROM python:3.6.1

## The maintainer name and email
MAINTAINER Richard Shaw <richard@phas.ubc.ca>

# Install any needed packages specified in requirements.txt
RUN apt-get update
RUN apt-get install -y ssh
RUN apt-get install -y rsync
RUN apt-get install -y netcat
RUN apt-get install -y mysql-client
RUN pip install mysqlclient

# Make port 80 available to the world outside this container
EXPOSE 22

# Run app.py when the container launches
CMD ["python"]
