#!/bin/bash

log=/var/log/alpenhorn/bandwidth_hogd.log

while [ 1 ]; do
  rm -rf /chime/data/bandwidth_hog_data/
  res=`rsync -aptr --stats --rsync-path="ionice -c2 -n5 rsync" -e "ssh -q" chime@gamelan.drao.nrc.ca:/var/chime/bandwidth_hog_data/ /chime/data/bandwidth_hog_data/ 2>&1`
  if [ -z "`echo $res | grep error`" ]; then
    echo "`date` `echo $res | awk '{printf("%s\n", $59);}'` byte/sec" >> $log
  else
    echo "`date` Rsync interrupted!" >> $log
  fi
done
