volumes:
  db_vol:
  node1_vol:
  node2_vol:
  node3_vol:
  transport_vol:
services:
  alpdb:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: alpenhorn_db
    volumes:
      - db_vol:/var/lib/mysql
  alpen1:
    build:
      context: ..
      dockerfile: demo/Dockerfile.alpenhorn
    image: alpenhorn
    command: sh -c "service ssh start && alpenhornd"
    depends_on:
      - alpdb
    hostname: alpen1
    volumes:
      - node1_vol:/data
      - transport_vol:/mnt/transport
  alpen2:
    image: alpenhorn
    command: sh -c "service ssh start && alpenhornd"
    depends_on:
      - alpdb
    hostname: alpen2
    volumes:
      - node2_vol:/data
  alpen3:
    image: alpenhorn
    command: sh -c "service ssh start && alpenhornd"
    depends_on:
      - alpdb
    hostname: alpen3
    volumes:
      - node3_vol:/data
      - transport_vol:/mnt/transport
