volumes:
  db_vol:
  node1_vol:
  node2_vol:
  node3_vol:
  transport_vol:
services:
  alpendb:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: alpenhorn_db
    hostname: alpendb
    volumes:
      - db_vol:/var/lib/mysql
  alpenshell:
    build:
      context: ..
      dockerfile: demo/Dockerfile.alpenhorn
    image: alpenhorn
    command: /bin/bash -l
    depends_on:
      - alpendb
    hostname: alpenshell
  alpenhost1:
    image: alpenhorn
    depends_on:
      - alpendb
    hostname: alpenhost1
    volumes:
      - node1_vol:/data
      - transport_vol:/mnt/transport
  alpenhost2:
    image: alpenhorn
    depends_on:
      - alpendb
    hostname: alpenhost2
    volumes:
      - node2_vol:/data
  alpenhost3:
    image: alpenhorn
    depends_on:
      - alpendb
    hostname: alpenhost3
    volumes:
      - node3_vol:/data
      - transport_vol:/mnt/transport
