---
name: Doc build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install pip dependencies
      run: pip install .[docs]

    - name: Build sphinx docs
      run: sphinx-build -W -b html doc/ doc/_build/html
